// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (C) 2026 <developer@mplx.eu>

//go:build ignore

// Command gen_codecs generates codecs_gen.go: the long-tail single-byte
// character codecs (ISO-8859-N, Windows-125N) as 256-rune tables, read from
// the authoritative Unicode Consortium mapping files so the data is exact
// rather than hand-transcribed.
//
// Run from the package directory (network required):
//
//	go generate ./internal/lib/encoding/
//
// or from anywhere with an explicit output path:
//
//	go run ./internal/lib/encoding/gen_codecs.go internal/lib/encoding/codecs_gen.go
//
// Only `ascii` (7-bit, with custom out-of-range errors) and `ebcdic`
// (IBM-1047, not in the standard Unicode mapping path) stay hand-written in
// codecs.go; every ISO-8859 and Windows single-byte codec is generated here
// so the tables come from one authoritative source. ISO-8859-12 was never
// standardised.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
)

const base = "https://www.unicode.org/Public/MAPPINGS/"

var gen = []struct{ name, url string }{
	{"iso-8859-1", base + "ISO8859/8859-1.TXT"},
	{"iso-8859-2", base + "ISO8859/8859-2.TXT"},
	{"iso-8859-3", base + "ISO8859/8859-3.TXT"},
	{"iso-8859-4", base + "ISO8859/8859-4.TXT"},
	{"iso-8859-5", base + "ISO8859/8859-5.TXT"},
	{"iso-8859-6", base + "ISO8859/8859-6.TXT"},
	{"iso-8859-7", base + "ISO8859/8859-7.TXT"},
	{"iso-8859-8", base + "ISO8859/8859-8.TXT"},
	{"iso-8859-9", base + "ISO8859/8859-9.TXT"},
	{"iso-8859-10", base + "ISO8859/8859-10.TXT"},
	{"iso-8859-11", base + "ISO8859/8859-11.TXT"},
	{"iso-8859-13", base + "ISO8859/8859-13.TXT"},
	{"iso-8859-14", base + "ISO8859/8859-14.TXT"},
	{"iso-8859-15", base + "ISO8859/8859-15.TXT"},
	{"iso-8859-16", base + "ISO8859/8859-16.TXT"},
	{"windows-1250", base + "VENDORS/MICSFT/WINDOWS/CP1250.TXT"},
	{"windows-1251", base + "VENDORS/MICSFT/WINDOWS/CP1251.TXT"},
	{"windows-1252", base + "VENDORS/MICSFT/WINDOWS/CP1252.TXT"},
	{"windows-1253", base + "VENDORS/MICSFT/WINDOWS/CP1253.TXT"},
	{"windows-1254", base + "VENDORS/MICSFT/WINDOWS/CP1254.TXT"},
	{"windows-1255", base + "VENDORS/MICSFT/WINDOWS/CP1255.TXT"},
	{"windows-1256", base + "VENDORS/MICSFT/WINDOWS/CP1256.TXT"},
	{"windows-1257", base + "VENDORS/MICSFT/WINDOWS/CP1257.TXT"},
	{"windows-1258", base + "VENDORS/MICSFT/WINDOWS/CP1258.TXT"},
}

// tableVar turns a codec name into its Go var identifier:
// "iso-8859-2" -> "iso88592Table", "windows-1250" -> "windows1250Table".
func tableVar(codec string) string {
	return strings.ReplaceAll(codec, "-", "") + "Table"
}

// fetchTable reads a Unicode mapping file (lines "0xBB<tab>0xUUUU # NAME";
// a byte with no code point is undefined) into a 256-rune table, with
// undefined positions left as U+FFFD (utf8.RuneError).
func fetchTable(url string) (*[256]rune, error) {
	var t [256]rune
	for i := range t {
		t[i] = 0xFFFD
	}
	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	sc := bufio.NewScanner(resp.Body)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		f := strings.Fields(line)
		if len(f) < 2 {
			continue // blank line or an undefined byte (no code point)
		}
		b, err := strconv.ParseUint(strings.TrimPrefix(f[0], "0x"), 16, 16)
		if err != nil || b > 0xFF {
			continue
		}
		cp, err := strconv.ParseUint(strings.TrimPrefix(f[1], "0x"), 16, 32)
		if err != nil {
			continue
		}
		t[b] = rune(cp)
	}
	return &t, sc.Err()
}

func main() {
	out := "codecs_gen.go"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// SPDX-License-Identifier: LGPL-3.0-only")
	fmt.Fprintln(&buf, "// Copyright (C) 2026 <developer@mplx.eu>")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "// Code generated by gen_codecs.go; DO NOT EDIT.")
	fmt.Fprintln(&buf, "// Source: Unicode Consortium mapping files (https://www.unicode.org/Public/MAPPINGS/).")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package encodinglib")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "func init() {")
	for _, g := range gen {
		fmt.Fprintf(&buf, "\tregisterTableCodec(%q, &%s, true)\n", g.name, tableVar(g.name))
	}
	fmt.Fprintln(&buf, "}")
	fmt.Fprintln(&buf)

	for _, g := range gen {
		t, err := fetchTable(g.url)
		if err != nil {
			log.Fatalf("%s (%s): %v", g.name, g.url, err)
		}
		fmt.Fprintf(&buf, "var %s = [256]rune{\n", tableVar(g.name))
		for i := 0; i < 256; i += 8 {
			buf.WriteByte('\t')
			for j := i; j < i+8; j++ {
				fmt.Fprintf(&buf, "0x%04X, ", t[j])
			}
			buf.WriteByte('\n')
		}
		fmt.Fprintln(&buf, "}")
		fmt.Fprintln(&buf)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v", err)
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s (%d codecs)\n", out, len(gen))
}
