#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-only
# Copyright (C) 2026 <developer@mplx.eu>
"""Regenerate the Jennifer wordmark lockups and the mdBook header injector.

Run from the repository root:  python3 scripts/genwordmark.py

Requires `fonttools` and the DejaVu Sans Mono Bold face (path in FONT below);
the 'jennifer' text is outlined to vector paths so the result renders
identically everywhere, with no font dependency at display time. The committed
SVGs are the source of truth - this script only needs to run when the wordmark
design changes.

Outputs:
  site/logo/jennifer-wordmark.svg       README lockup, ink text (the <img> default)
  site/logo/jennifer-wordmark-dark.svg  README lockup, paper text (prefers-color-scheme:dark)
  theme/logo.js                         injects an inline header lockup whose text is
                                        currentColor (inherits mdBook's per-theme foreground)
"""
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

FONT = "/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf"
TEXT = "jennifer"
FS = 62.0
MARK_W = 100.0
GAP = 30.0
PADR = 12.0
CENTER_Y = 50.0

font = TTFont(FONT)
upem = font["head"].unitsPerEm
scale = FS / upem
glyphSet = font.getGlyphSet()
cmap = font.getBestCmap()

glyphs = []
x = 0.0
xmin = ymin = 1e9
xmax = ymax = -1e9
for ch in TEXT:
    g = glyphSet[cmap[ord(ch)]]
    pen = SVGPathPen(glyphSet)
    g.draw(pen)
    d = pen.getCommands()
    bp = BoundsPen(glyphSet)
    g.draw(bp)
    if d:
        glyphs.append((d, x))
        if bp.bounds:
            gx0, gy0, gx1, gy1 = bp.bounds
            xmin = min(xmin, x + gx0 * scale)
            xmax = max(xmax, x + gx1 * scale)
            ymin = min(ymin, -gy1 * scale)
            ymax = max(ymax, -gy0 * scale)
    x += g.width * scale

dx = (MARK_W + GAP) - xmin
dy = CENTER_Y - (ymin + ymax) / 2.0
word_w = xmax - xmin
total_w = MARK_W + GAP + word_w + PADR

glyph_lines = "\n".join(
    f'    <path d="{d}" transform="translate({gx:.3f},0) scale({scale:.6f},{-scale:.6f})"/>'
    for d, gx in glyphs
)

MARK = (
    '  <rect width="100" height="100" rx="26" fill="#1B1420"/>\n'
    '  <g fill="none" stroke="#EC5C4B" stroke-width="12" stroke-linecap="round" stroke-linejoin="round">\n'
    '    <path d="M35 33 H67"/>\n'
    '    <path d="M61 33 V54 C61 70 49 74 39.5 70.5 C33 68 31 61 31.5 56.5"/>\n'
    '  </g>'
)

# --- README lockups: fixed-colour light + dark variants, swapped by <picture> ---
def lockup(fill, note):
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: LGPL-3.0-only -->
<!-- Copyright (C) 2026 <developer@mplx.eu> -->
<!-- Jennifer wordmark lockup: monogram + 'jennifer' (DejaVu Sans Mono Bold, outlined).
     {note} The mark tile is self-contained; a <picture> element picks the variant. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {total_w:.2f} 100" width="{total_w:.2f}" height="100" role="img" aria-label="Jennifer">
  <title>Jennifer</title>
{MARK}
  <g fill="{fill}" transform="translate({dx:.3f},{dy:.3f})">
{glyph_lines}
  </g>
</svg>
'''

with open("site/logo/jennifer-wordmark.svg", "w") as f:
    f.write(lockup("#241C29", "Ink text, for light backgrounds (the <img> default)."))
with open("site/logo/jennifer-wordmark-dark.svg", "w") as f:
    f.write(lockup("#F2ECE6", "Paper text, for dark backgrounds (the prefers-color-scheme:dark source)."))

# --- Header variant: text uses currentColor (inherits mdBook theme foreground) ---
header_svg = (
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {total_w:.2f} 100" '
    f'role="img" aria-label="Jennifer"><title>Jennifer</title>'
    f'<rect width="100" height="100" rx="26" fill="#1B1420"/>'
    f'<g fill="none" stroke="#EC5C4B" stroke-width="12" stroke-linecap="round" stroke-linejoin="round">'
    f'<path d="M35 33 H67"/>'
    f'<path d="M61 33 V54 C61 70 49 74 39.5 70.5 C33 68 31 61 31.5 56.5"/></g>'
    f'<g fill="currentColor" transform="translate({dx:.3f},{dy:.3f})">'
    + "".join(
        f'<path d="{d}" transform="translate({gx:.3f},0) scale({scale:.6f},{-scale:.6f})"/>'
        for d, gx in glyphs
    )
    + "</g></svg>"
)

logo_js = (
    "// SPDX-License-Identifier: LGPL-3.0-only\n"
    "// Copyright (C) 2026 <developer@mplx.eu>\n"
    "//\n"
    "// Replaces the mdBook menu-bar title with the Jennifer wordmark lockup.\n"
    "// The 'jennifer' text is currentColor, so it inherits the active mdBook\n"
    "// theme's foreground and stays legible on light / ayu / coal / navy / rust.\n"
    "// Registered via book.toml [output.html] additional-js.\n"
    "// Generated by scripts/genwordmark.py; do not hand-edit.\n"
    "(function () {\n"
    "  var SVG = " + repr(header_svg) + ";\n"
    "  function place() {\n"
    "    var t = document.querySelector('.menu-title');\n"
    "    if (!t || t.dataset.jlogo) return;\n"
    "    t.dataset.jlogo = '1';\n"
    "    t.setAttribute('aria-label', 'Jennifer');\n"
    "    t.classList.add('has-logo');\n"
    "    t.innerHTML = SVG;\n"
    "  }\n"
    "  if (document.readyState !== 'loading') place();\n"
    "  else document.addEventListener('DOMContentLoaded', place);\n"
    "})();\n"
)
with open("theme/logo.js", "w") as f:
    f.write(logo_js)

print(f"wordmark viewBox width={total_w:.1f}; wrote both wordmark SVGs + theme/logo.js")
